### ISSUE TITLE
Quick report from map list for unknown tempests

### ISSUE THREAD

**Issue by jayvan** [jayvan/tempest-watch#13]
> I have a feature request, when you check if there is an active tempest in a map, it would be nice if you could click the map to create a report for that map right away.
> At least if the map is listed as "unknown tempest"

**Comment by MMcCormick** [comment]
I like this idea

**Comment by MMcCormick** [comment]
Want me to hop on this?

**Comment by jayvan** [comment]
Sure, code can be very similar to the `downvote`, just need to populate the form and navigate to the report tab

**Comment by jayvan** [comment]
I'll probably implement this tomorrow night. I'll post here before I start, if you'd like to do it before then definitely go ahead!

**Comment by MMcCormick** [comment]
I'm partway into an idea, let's chat about implementation

**Comment by MMcCormick** [comment]
Working on this, should be done soon!

**Comment by jayvan** [comment]
Closed by @MMcCormick in #22
