### ISSUE TITLE
API for list of tempests

### ISSUE THREAD

**Issue by jayvan** [jayvan/tempest-watch#2]
To make 3rd party tools easier, it would be nice if there was an API to get the list of tempest names.

**Comment by MMcCormick** [comment]
I'd be happy to start on this

**Comment by jayvan** [comment]
Sure!

The logical route for it would be`/api/tempests`, but that route shows all of the locations & their active tempests currently. I'm open to renaming the original if you can come up with a better name for it :)

**Comment by jayvan** [comment]
maybe `api/current_tempests` for the existing route, and `api/tempests` for the new one? Depending how warbands work it'd be neat to add support for tracking them in maps in the future so `api/current_warbands` and `api/warbands` could work similarly

**Comment by MMcCormick** [comment]
Definitely. I think changing that structure is more adaptable, but let me think about something shorter. In fact, maybe `tempests/current` or just `tempests` with a filter for the current ones makes the most sense. I'll check out the structure.

**Comment by jayvan** [comment]
Resolved in ee7a110fae26f065e20e855dae5a261f3027ea70
