### ISSUE TITLE
API discussion

### ISSUE THREAD

**Issue by pajlada** [jayvan/tempest-watch#21]
In the `current_tempests` endpoint (http://poetempest.com/api/v1/current_tempests), the base+suffix are returned as the description of the affixes, whereas for the `vote` endpoint, it requires me to pass through the affix name.

This makes it a lot trickier than necessary. I have multiple options here:
- Parse the `name` of the tempest (i.e. `Enlarging Tempest of Desperation`) and pass that
- Fetch the tempest affix data from the `tempests` endpoint (http://poetempest.com/api/v1/tempests), reverse it and use the `base` and `suffix` description of the tempest to get the accompanying affix name.

In my opinion, the `current_tempests` endpoint should return the prefix and suffix name, like this:

``` json
{
  "crypt": {
    "name": "Abyssal Tempest of Animation",
    "base": "abyssal",
    "suffix": "animation",
    "votes": 18,
    "type": "dangerous"
  },
  "desert": {
    "name": "Unknown Tempest",
    "base": "",
    "suffix": "",
    "votes": 0,
    "type": ""
  }
}
```

If we require the tempest description, we can easily match the affixes given to us with the data received from the `tempests` endpoint

**Comment by jayvan** [comment]
Makes complete sense to me.

**Comment by kjy112** [comment]
I wanted to add  my comment on this but this was closed. Perhaps, add two more fields to the object with instance 'base desc' and suffix desc' along with this change?

**Comment by pajlada** [comment]
My idea was that you can fetch tempest descriptions from here: http://poetempest.com/api/v0/tempests and match affix names yourself, just as you do with map and their levels (http://poetempest.com/api/v0/maps)

**Comment by kjy112** [comment]
That works as well.

**Comment by jayvan** [comment]
Yeah, since the descriptions rarely change, I think it's best to keep them in the separate tempests API call, you can make it once and store them in a dictionary. Keeps the current tempest responses much shorter.
