### ISSUE TITLE
Looking for help, automated tempest reporting

### ISSUE THREAD

**Issue by pajlada** [jayvan/tempest-watch#26]
I'm currently developing a Windows application which makes use of the poetempest.com API.

What I'm trying to finalize now is a feature which would let users click a single button to report the tempest of their current map. Here's a gif of it in progress:

![a](http://i.imgur.com/kwUSgG5.gif)

What I would need from you guys, is raw .png screenshots from when you're in maps (with or without tempests) with TAB pressed (so you see map name and tempest data in the top right corner), like this image: ![b](http://i.imgur.com/9y14mSG.png)

With these screenshots I can improve the methods of parsing map name and tempest data, and make sure it gives as few false positives as possible.

Pressing F8 in game takes a raw screenshot of the game and puts it in the following folder: C:\Users<YOUR USERNAME>\Documents\my games\Path of Exile\Screenshots

Raw images are preferred, they can be emailed to me at pajlada@bithack.se or uploaded to this github issue as a response comment.
If that's too inconvenient, uploading them to any image host (i.e. [imgur](http://imgur.com)) should hopefully also work without too heavily compressing the image.

Thanks for reading!

**Comment by jayvan** [comment]
Looks great. I'll ask around for people to help submit training screenshots.

**Comment by jayvan** [comment]
If you ask on the PoE subreddit I'm sure you'll get lots of submissions!

**Comment by shlnz** [comment]
I tried it with a similar approach using Tesseract-OCR, but have no time right now to test it more. Hope you get closer.

**Comment by pajlada** [comment]
@shlnz I'm using tesseract as well, together with some image manipulation with the help of ImageMagick. All source code is available at: https://github.com/pajlada/TempestNotifier

The methods I'm trying out now are the following:
First, crop the screenshot to only include the map area and the tempest area (or first "map modifier").
Then I perform Scaling/Monochroming/Sharpening/Blurring of the two images, and run the OCR-code on ALL result images.

Here's an album with all the images I use/process: http://imgur.com/a/pO5UW

I'll definitely try reddit later tonight, thanks for the suggestion!
