### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by MMcCormick** [jayvan/tempest-watch#3]
@jayvan how do you feel about testing? I think rspec would help me make sure we keep older versions of the API working as we find out more. Ideally, you wouldn't need to implement anything outside of what I do (unless you'd like to)

**Comment by jayvan** [comment]
Testing is great, I've held off for now since we don't really know 100% how
tempests work yet. If you'd like to get something in place that would be
awesome! Looking to freeze the API the day after the expansion is released.

**Comment by jayvan** [comment]
Testing has been added for the `/api/v0/tempests` route :+1: 
Feel free to increase coverage, I'll work on specs this weekend once we have `v1` and we're happy with it :)
