### ISSUE TITLE
add a description of what the tempest and suffix does on the report page

### ISSUE THREAD

**Issue by charlotteqt** [jayvan/tempest-watch#5]
I've been told people aren't using it because they don't know what the tempest/suffix is called even though they know what it's doing in the map.

**Comment by jayvan** [comment]
What do you think of this?

![description_inline](https://cloud.githubusercontent.com/assets/639944/8712469/8e12c04e-2b2a-11e5-819d-3d3e76907b97.PNG)

**Comment by MMcCormick** [comment]
:+1: Definitely can't hurt!

**Comment by charlotteqt** [comment]
Seems good.

Might be a little harder with the suffixes since a lot of people don't really realise they're a thing.

For example, according the poedb page there's a suffix which makes a random mob in the map drop a unique and another  that makes a random mob drop a map.

I guess the obvious ones are easy though (20 exiles.)

**Comment by jayvan** [comment]
Chris mentioned that they are going to be adding the tempest information under the minimap in game. I'm going to hold off on this, there isn't much space to fit long descriptions in the drop down.

**Comment by jayvan** [comment]
The name of the tempest is now displayed in game.
