### ISSUE TITLE
Highlight valueable tempests

### ISSUE THREAD

**Issue by jayvan** [jayvan/tempest-watch#6]
Suggestion via email.

> Could you add a colored highlight on maps with very valuable tempest(iiq/iir, 20 exiles etc) so that you could see very fast which map has a good mob.

**Comment by MMcCormick** [comment]
i'm on it.

**Comment by jayvan** [comment]
Great! Thanks @MMcCormick

**Comment by MMcCormick** [comment]
@jayvan thinking it through, i think it would be great to color code "no tempest", "dangerous tempest", and "unknown" too. cool?

**Comment by jayvan** [comment]
Sounds good to me.

**Comment by jayvan** [comment]
Closed by @MMcCormick in https://github.com/jayvan/tempest-watch/commit/6ef0f390f5933692e82ecff875f74dc5a1378ec4
